accessible: true
author: François MICHEL & Clémentine MUNYABARENZI & Mawait MAXIME & Visée WILLIAM
    & Habran ANTOINE
context: |+
    Les boucles, notamment les boucles ``for``, sont un concept clé en programmation. Pour vous entraîner à l'utilisation de boucles ``for``, écrivez une boucle for qui permettra de calculer la somme des n premiers entier PAIRS supérieurs à zéro, en fonction de la variable n, déjà définie à une valeur supérieure ou égale à zéro. Le résultat final doit être stocké dans la variable ``sum`` à la fin de la boucle, elle aussi déjà définie. Lorsque n est négatif, le résultat doit valoir zéro.

    Exemple: si ``n`` = 2, ``sum`` = 2 + 4 = 6

    .. code-block:: java

        int n = /* n peut prendre n'importe quelle valeur */
        int sum = 0;

environment: mcq
evaluate: best
groups: false
limits:
    memory: '200'
    time: '30'
    output: '2'
name: 'Mission 2: Question de démarrage 2 : Somme d''entiers'
network_grading: false
order: 5
problems:
    q1:
        type: code
        header: 'Écrivez ici le bout de programme permettant de calculer la somme
            des n premiers entiers pairs :'
        name: Somme des n premiers entiers pairs
        language: Java
stored_submissions: 0
submission_limit:
    amount: -1
    period: -1
weight: 1.0
