accessible: true
author: Fitvoye Florian, Dubray Alexandre
context: Créez une méthode "cut" qui sépare un String donné et affiche tout les sous
    String.
environment: java7
groups: false
limits:
    memory: '100'
    time: '30'
    output: '2'
name: 'Mission 04 : Question 03 : Découper un String'
network_grading: false
problems:
    q1:
        language: java
        type: code
        name: Cut
        header: |-
            Voici la signature de la fonction :

            .. code-block:: java

                /*
                 * pre : str est un String non vide
                 * post: la fonction separe str a chaque c et affiche tout les sous String
                 * exemple : str = "bonjour.hello.java" et c='.' affiche bonjour, hello et java chacun sur une ligne
                 */
                public static void cut (String str, char c){
                    /* code a completer */
                }
weight: 1.0
