accessible: true
author: Aurélie MASSART, Alexandre KÜHN & Hua Yang HU
context: |
    Soit un stack défini par la classe suivante :

    .. code-block:: java

        public class Node{
            int value;
            Node next;

            ...
        }

    .. code-block:: java

        public class Stack{
            Node first;

            ...
        }

    La classe Stack est incomplète : il manque les opérations push et pop ajoutant un élément et retirant un élément du stack. Répondez aux différentes questions théoriques ci-dessous.
environment: java7
groups: false
limits:
    memory: '200'
    output: '2'
    time: '30'
name: 'Mission 11 : Question de démarrage 8 : Opérations sur un stack : théorie'
network_grading: false
order: 9
problems:
    q1:
        type: multiple-choice
        name: Retrait d'un élément du stack
        header: 'La fonction pop permet de retirer un élément du stack. Le stack est
            ici représenté par une liste de Node. Par définition, l''élément est supprimé
            du (de) :'
        choices:
        -   text: début de la liste
            valid: true
        -   text: fin de la liste
        limit: 0
    q2:
        choices:
        -   text: début de la liste
            valid: true
        -   text: fin de la liste
        name: Ajout d'un élément dans le stack
        type: multiple-choice
        header: 'La fonction push permet dajouter un élément sur le stack. Le stack
            est ici représenté par une liste de Node. Par définition, l''élément est
            ajouté au (à) :'
        limit: 0
weight: 1.0
