accessible: true
author: Aurélie MASSART, Alexandre KÜHN & Hua Yang HU, Mawait Maxime
context: |
    Soit une liste d'entiers doublement chainée triée en ordre CROISSANT. La liste est implémentée par la classe Node décrite comme :

    .. code-block:: java

        public class Node{
            int value;
            Node next;
            Node previous;

            ...
        }

    où next représente le Node suivant dans la liste et previous représente le Node précédent.
    On veut retourner l'élément maximum de la liste triée. Indiquez le fragment de code nécessaire pour réaliser cette opération.
environment: java7
evaluate: best
groups: false
limits:
    memory: '200'
    output: '2'
    time: '30'
name: 'Mission 11 : Question intermédiare 2 : Maximum d''une liste triée'
network_grading: false
order: 11
problems:
    q1:
        header: |
            Écrivez ici le fragment de code retournant le maximum de la liste triée. Voici les spécifications et la signature de la méthode à implémenter. Dans votre réponse, ne fournissez que les lignes de code internes à la fonction mais ne recopier pas la signature de la fonction. Faites attention à ne pas modifier dans votre fonction la liste donnée en argument. Attention à utiliser la programmation défensive pour vérifier les préconditions.

            .. code-block:: java

                /*
                 * @pre n != null
                 * @post retourne le maximum de la liste doublement chainée triée n
                 */
                public static int maximum(Node n){
                    //à compléter
                }
        language: java
        name: 'Trouver le maximum d''une liste '
        type: code
stored_submissions: 0
submission_limit:
    amount: -1
    period: -1
weight: 1.0
