accessible: true
author: Aurélie MASSART, Alexandre KÜHN & Hua Yang HU, Mawait Maxime
context: |
    Soit une liste doublement chainée. La liste est implémentée par la classe Node décrite comme :

    .. code-block:: java

        public class Node{
            int value;
            Node next;
            Node previous;

            ...
        }

    On veut retourner l'élément minimum de la liste. Attention, la liste n'est PAS triée. Indiquez le fragment de code nécessaire pour retourner le minimum d'une telle liste.
environment: java7
evaluate: best
groups: false
limits:
    memory: '200'
    output: '2'
    time: '30'
name: 'Mission 11 : Question intermédiaire 3 : Minimum d''une liste'
network_grading: false
order: 12
problems:
    q1:
        header: |
            Écrivez ici le fragment de code retournant le minimum de la liste. Voici les spécifications et la signature de la méthode à implémenter. Dans votre réponse, ne fournissez que les lignes de code internes à la fonction mais ne recopiez pas la signature de la fonction. Faites attention à ne pas modifier dans votre fonction la liste donnée en argument. Faites attention à utiliser la programmation défensive pour vérifier les pré-conditions.

            .. code-block:: java

                /*
                 * @pre n != null
                 * @post retourne le minimum de la liste doublement chainée n
                 */

                public static int minimum(Node n) {
                    // à compléter
                }
        language: java
        name: 'trouver le minimum d''une liste '
        type: code
stored_submissions: 0
submission_limit:
    amount: -1
    period: -1
weight: 1.0
