accessible: true
author: Lucas Ody & Tom Rousseaux
context: |-
    Les coefficients d'une équation de 3ème degré vous sont donnés. A vous d'en trouver une des solutions entières, qui se trouve entre 0 et 20 inclus, en utilisant une boucle pour tester ces possibilités. Stockez votre réponse dans la variable ``r``.


    .. code-block:: java
        int xCube;//le coefficient du x³

        int xCarre;//le coefficient du x²

        int x; // Le coefficient du x

        int tI; // Le terme indépendant

        int r = 0; //La variable contenant la reponse du probleme
environment: java7
evaluate: best
groups: false
limits:
    output: '2'
    time: '30'
    memory: '100'
name: 'Mission 01 : Question 03 : Solution d''une équation'
network_grading: false
order: 2
problems:
    q1:
        type: code
        name: solution de l'équation
        header: ''
        language: java
stored_submissions: 0
submission_limit:
    amount: -1
    period: -1
weight: 1.0
