accessible: true
author: Lucas Ody & Tom Rousseaux 
context: |-
    À partir d'un produit de 3 polynomes de 1er degré, dont l'expression est ``(x-a)(x-b)(x-c)``. Vous devez retrouver les coefficients du polynome de 3ème dégré résultant d'une distribution, et les stocker dans leur variables respectives.


    .. code-block:: java

        int a,b,c; //les racines

        int xCube = 0;//le coefficient du x³

        int xCarre = 0;//le coefficient du x²

        int x = 0;//le coefficient du x

        int tI = 0;//le terme independant
environment: java7
groups: false
limits:
    memory: '100'
    time: '30'
    output: '2'
name: 'Mission 1 : Multiplication algébrique'
network_grading: false
order: 3
problems:
    q1:
        language: java
        type: code
        name: ''
        header: ''
weight: 1.0
